# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_shop?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
# Hibernate (JPA) Settings
# 'update' automatically creates or updates database tables based on your Java classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sandeshhiremath2004@gmail.com
spring.mail.password=vrvkefbowidqsbrkv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true